
{"command": "laczenie", "content": "A=T lub A=U jesli RNA G=C", "owner": "David", "access": "u-r"}
{"command": "DNA", "content": "DNA wystepuje w jadrze komorkowym, mitochondriach itp.", "owner": "David", "access": "u-r"}
{"command": "???", "content": "nic", "owner": "David", "access": "u-n"}
{"command": "hbo", "content": "Pierwiastki to podstawowe elemnty budujace organizm. Lacza sie one w zwiazki chemiczne miedzy innymi w bialka ktore buduja skladniki komorki. Komorki tworza tkanki. Z tkanek powstaja narzady. Ktore wspolpracuje ze soba uklady narzadow i tworza organizm", "owner": "David", "access": "u-r"}
{"command": "zwiazkiChemiczne", "content": "Wsrod zwiazkow chemicznych wyroznia sie Zwiazki organiczne np lipidy, bialka , weglowodany i kwasy nukleinowe wyrozniamy takze zwiazki nieorganiczne do ktorych nalezy woda i sole minerlane", "owner": "David", "access": "u-r"}
{"command": "info", "content": "hbo to Hierchiczna budowa organizmow", "owner": "David", "access": "u-n"}
{"command": "makroelementy", "content": "Makroelementy to pierwiastki ktore wystepuje w organizmie w duzych ilosciach(stanowia o,01% lub wiecej jego suchej masy). Zaliczmy do nich jedenascie pierwiastkow. Szesc z nich nazywa sie pierwiastkami biogennymi poniewaz sa one glownymi skladnikammi zwiazkow organicznych budujacych wszystkie organizmy. Sa to wegiel(C) wodor(H) tlen azot(N) fosfor(P) i siarka(S). Pozostale piec to wapn(Ca) magnez potas(K) sod(Na) i chlor", "owner": "David", "access": "u-r"}
{"command": "mikroelementy", "content": "Mikro elementy to pierwiastki, ktore wystepuja w organizmie w niewielkich ilosciach(mniez niz 0,01% suchej masy). Zaliczamy do nich np zelazo(Fe) miedz(Cu) jod(I) flour(F) i kobalt(Co). Te pierwiastki reguluja wiele czynnosci i procesow zyuciowych", "owner": "David", "access": "u-r"}
{"command": "tlen", "content": "Tlen jest skladnikiem zwiazkow organicznych. Jest substratem oddychania tlenowego zachodzacego w mitochondrium", "owner": "David", "access": "u-r"}
{"command": "wegiel", "content": "Wegiel jest skladnikiem wszystkich zwiazkow organicznych. Zwiazki wegla glownie glukoza stanowia substrat oddychania tlenowego", "owner": "David", "access": "u-r"}
{"command": "wodor", "content": "Wodor jest skladnikiem zwiazkow organicznych. W postaci jonow decyduje o pH plynow ustrojowych np krwi i limfy. Bierze udzial w wytwarzaniu ATP(nosnika energii) w mitochondriach", "owner": "David", "access": "u-r"}
{"command": "azot", "content": "Azot jest skladnikiem kwasow nukleinowych i bialek", "owner": "David", "access": "u-r"}
{"command": "fosfor", "content": "Fosfor jest skladnikiem kwasow nukleinowych. Wystepuje w ATP. Fosforan wapnia buduje kosci i zeby", "owner": "David", "access": "u-r"}
{"command": "siarka", "content": "Siarka jest skladnikiem wielu bialek wystepuje np w bialkach budujacych wlosy i paznokcie", "owner": "David", "access": "u-r"}
{"command": "wapn", "content": "Wapn jest niezbedny do prawidlowego funkcjonowania komorek miesniowych i nerwowych. Buduje kosci oraz uczestniczy w krzepnieciu krwi", "owner": "David", "access": "u-r"}