
{"command": "laczenie", "content": "A=T lub A=U jesli RNA G=C", "owner": "David", "access": "u-r"}
{"command": "DNA", "content": "DNA wystepuje w jadrze komorkowym, mitochondriach itp.", "owner": "David", "access": "u-r"}
{"command": "???", "content": "nic", "owner": "David", "access": "u-n"}
{"command": "hbo", "content": "Pierwiastki to podstawowe elemnty budujace organizm. Lacza sie one w zwiazki chemiczne miedzy innymi w bialka ktore buduja skladniki komorki. Komorki tworza tkanki. Z tkanek powstaja narzady. Ktore wspolpracuje ze soba uklady narzadow i tworza organizm", "owner": "David", "access": "u-r"}
{"command": "zwiazkiChemiczne", "content": "Wsrod zwiazkow chemicznych wyroznia sie Zwiazki organiczne np lipidy, bialka , weglowodany i kwasy nukleinowe wyrozniamy takze zwiazki nieorganiczne do ktorych nalezy woda i sole minerlane", "owner": "David", "access": "u-r"}
{"command": "info", "content": "hbo to Hierchiczna budowa organizmow", "owner": "David", "access": "u-n"}
{"command": "makroelementy", "content": "Makroelementy to pierwiastki ktore wystepuje w organizmie w duzych ilosciach(stanowia o,01% lub wiecej jego suchej masy). Zaliczmy do nich jedenascie pierwiastkow. Szesc z nich nazywa sie pierwiastkami biogennymi poniewaz sa one glownymi skladnikammi zwiazkow organicznych budujacych wszystkie organizmy. Sa to wegiel(C) wodor(H) tlen azot(N) fosfor(P) i siarka(S). Pozostale piec to wapn(Ca) magnez potas(K) sod(Na) i chlor", "owner": "David", "access": "u-r"}
{"command": "mikroelementy", "content": "Mikro elementy to pierwiastki, ktore wystepuja w organizmie w niewielkich ilosciach(mniez niz 0,01% suchej masy). Zaliczamy do nich np zelazo(Fe) miedz(Cu) jod(I) flour(F) i kobalt(Co). Te pierwiastki reguluja wiele czynnosci i procesow zyuciowych", "owner": "David", "access": "u-r"}
{"command": "tlen", "content": "Tlen jest skladnikiem zwiazkow organicznych. Jest substratem oddychania tlenowego zachodzacego w mitochondrium", "owner": "David", "access": "u-r"}
{"command": "wegiel", "content": "Wegiel jest skladnikiem wszystkich zwiazkow organicznych. Zwiazki wegla glownie glukoza stanowia substrat oddychania tlenowego", "owner": "David", "access": "u-r"}
{"command": "wodor", "content": "Wodor jest skladnikiem zwiazkow organicznych. W postaci jonow decyduje o pH plynow ustrojowych np krwi i limfy. Bierze udzial w wytwarzaniu ATP(nosnika energii) w mitochondriach", "owner": "David", "access": "u-r"}
{"command": "azot", "content": "Azot jest skladnikiem kwasow nukleinowych i bialek", "owner": "David", "access": "u-r"}
{"command": "fosfor", "content": "Fosfor jest skladnikiem kwasow nukleinowych. Wystepuje w ATP. Fosforan wapnia buduje kosci i zeby", "owner": "David", "access": "u-r"}
{"command": "siarka", "content": "Siarka jest skladnikiem wielu bialek wystepuje np w bialkach budujacych wlosy i paznokcie", "owner": "David", "access": "u-r"}
{"command": "wapn", "content": "Wapn jest niezbedny do prawidlowego funkcjonowania komorek miesniowych i nerwowych. Buduje kosci oraz uczestniczy w krzepnieciu krwi", "owner": "David", "access": "u-r"}
{"command": "magnez", "content": "Magnez jest niezbedny do prawwidlowego funkcjonowania komorek miesniowych i nerwowych. Reguluje dzialanie enzymow. Magnez to takze dobry srodek na stres problemy z pamiecia koncentracja i praca miesni szkieletowych oraz sercem.", "owner": "David", "access": "u-r"}
{"command": "sodIPotas", "content": "Biora udzial w przewodzeniu impulsow nerwowych uczestnicza w ergulowanie cisnienia krwi oraz ilosci wody w organizmie", "owner": "David", "access": "u-r"}
{"command": "chlor", "content": "Chlor jest skladnikiem plynow ustrojowych i jest skladnikiem soku zoladkowego", "owner": "David", "access": "u-r"}
{"command": "zelazo", "content": "Zelazo wchodzi w sklad n[ hemoglobiny - bialka dzieki ktoremu erytrocyty transportuja tlen", "owner": "David", "access": "u-r"}
{"command": "miedz", "content": "Miedz jest skladnikiem enzymow ktore uczesnicza w uzyskaniu energi. Uczestniczy w tworzeniu melanin(barwnikow skory)", "owner": "David", "access": "u-r"}
{"command": "jod", "content": "Jod jest skladnikiem hormonow tarczycy przez co wplywa na prace serca i ukladu nerwowego oraz na przemianu materii", "owner": "David", "access": "u-r"}
{"command": "fluor", "content": "Fluor jest skladnikiem szkliwa ktora zabezpiecza zeby przed uszkodzeniami chemicznymi np przed kwasami wytwarzanymi przez bakterie", "owner": "David", "access": "u-r"}
{"command": "kobalt", "content": "Kobalt jest skladnikiem witaminy B12 ktora bierze udzial w powstawaniu erytrocytow", "owner": "David", "access": "u-r"}
{"command": "skutkiNiedoborow", "content": "Tlen: Powazne problemy z oddychaniem, sinica, oslabienie funkcji mozgu. Wegiel: Zaburzenia w metabolizmie, spadek energii, problemy z rownowaga kwasowo-zasadowa. Wodor: Ograniczenie produkcji kwasow zoladkowych, problemy z trawieniem. Azot: Spadek produkcji bialek, oslabienie miesni, problemy z odpornoscia. Fosfor: Oslabienie kosci, problemy z metabolizmem. Siarka: Zaburzenia w budowie bialek, oslabienie ukladu odpornosciowego. Wapn: Oslabienie kosci, ryzyko osteoporozy, skurcze miesni. Magnez: Zaburzenia rytmu serca, oslabienie miesni, problemy z ukladem nerwowym. Sod: Problemy z rownowaga plynow w organizmie, oslabienie, zawroty glowy. Potas: Oslabienie miesni, problemy z funkcjonowaniem ukladu nerwowego. Chlor: Zaburzenia rownowagi kwasowo-zasadowej, problemy z trawieniem.", "owner": "David", "access": "u-r"}
{"command": "artykulySpozywcze", "content": "Tlen: Jajka, migdaly, brokuly. Wegiel: Pieczywo pelnoziarniste, brazowy ryz, platki owsiane. Wodor: Woda, orzechy, warzywa lisciaste. Azot: Mieso, ryby, jaja. Fosfor: Orzechy, pestki dyni, ciecierzyca. Siarka: Cebula, czosnek, jaja. Wapn: Mleko, jogurt, ser. Magnez: Szpinak, orzechy, fasola. Sod: Sol, produkty morskie, pomidory. Potas: Banany, ziemniaki, suszone owoce. Chlor: Sol kuchenna, ogorki kiszone, salata.", "owner": "David", "access": "u-r"}
{"command": "woda", "content": "Woda jest glownym zwiazkiem nieorganicznym wchodzacym w sklad wszystkich organizmow. Jej czasteczki sa zbudowane z atomow wodoru i tlenu. Zawartosc wody w organizmach jest rozna zalezy ona np od tego jak bardzo aktywny jest organizm w jakim srodowisku zyje czy jest zdrowy czy chory a takze na jakim etapie rozwoju sie znajduje Ponadto poszczegolne struktory jednego organizmu rowniez zawieraja odmienna ilosc wody", "owner": "David", "access": "u-r"}
{"command": "czasteczkaWody", "content": "Ma budowe polarna ma dwa bieguny dodatni i ujemny", "owner": "David", "access": "u-r"}
{"command": "budowaPolarna", "content": "Dzieki tej budowie czasteczki wody moga laczyc sie ze soba w wieksze zespoly za pomoca wiazan wodorowych. W ten sposob tworza sie m.in krople wody", "owner": "David", "access": "u-r"}
{"command": "wodaWNarzadach", "content": "Woda stanowi ok 65% jego masy u doroslego Szkliwo 3% | kosci 25% | watroba 68% | skora 72% | mozg 75% | oko 99%", "owner": "David", "access": "u-r"}
{"command": "znaczenieWody", "content": "Woda jest dobrym rozpuszczalnikiem Znaczenie dzieki temu stanowi srodowisko w ktroym moga zachodzic reakcje chemiczne. Woda umozliwia tez transport zwiazkow chemicznych | Gestosc wody zalezy od temperatury( najwieksza gest przy 4C. Woda o wiekszej gestosci opada na dno dlatego zima na dnia zbiornikow wodnych pozostaje w stanie cieklym Znaczenie Pozwala to organizmom wodnym przetrwac zime pod lodem | Woda ma duze napiecie powierzchniowe", "owner": "David", "access": "u-r"}
{"command": "znaczenieWodyTwo", "content": "Pozwala to niewielkim owadom utrzymac sie na jej powierzchni | Woda ma wysokie cieplo parowania Zmienia stan skupienia z cieklego na gazowy dostarcza to do niej duza ilosc energi Umozliwia to organizmom termoregulacje", "owner": "David", "access": "u-r"}
{"command": "znaczenieWodyTree", "content": "Woda ma duze cieplo wlasciwe aby podniesc temperature wody, nalezy dostarczyc jej znaczna ilosc energi cieplen Natomiast aby obnizyc temperature trzeba duza ilosc energi zabrac Chroni to organizmy przed naglymi zmianami temperatury otocenia i umozliwia utrzymanie stalej temperatury ciala", "owner": "David", "access": "u-r"}